version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs
   system_packages: false
