pool:
  vmImage: 'macOS-10.15'

strategy:
  matrix:
    Python38:
      python.version: '3.8'
      TOXENV: py38
    Python39:
      python.version: '3.9'
      TOXENV: py39
    Python310:
      python.version: '3.10'
      TOXENV: py310

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: pip install -U wheel tox coveralls coverage[toml] setuptools setuptools_scm[toml]
  displayName: 'Install Tox'

- script: |
    tox
  env:
    PYTEST_ADDOPTS: "--cov-config=pyproject.toml --cov --cov-append --benchmark-skip"
  displayName: 'Run Tox'
